ServerEvents.recipes(event => {
    event.remove({ id: 'palmon:crafting/shapeless/plank_from_wood' })
    event.remove({ id: 'sophisticatedbackpacks:backpack' })
    event.remove({ id: 'botania:mana_infusion/mana_cookie' })
    event.remove({ id: 'sophisticatedbackpacks:iron_backpack' })
    event.remove({ id: 'sophisticatedbackpacks:iron_backpack_from_copper' })
    event.remove({ id: 'quark:building/crafting/furnaces/deepslate_furnace' })
    event.remove({ id: 'nethersdelight:blackstone_furnace' })
    event.remove({ id: 'quark:building/crafting/furnaces/blackstone_furnace' })
    event.remove({ id: 'palmon:crafting/shapeless/empty_contract' })
    event.remove({ id: 'palmon:crafting/shaped/processing_station' })
    event.remove({ id: 'palmon:crafting/shaped/production_machine' })
    event.remove({ id: 'ad_astra:nasa_workbench' })
    event.remove({ id: 'ad_astra:steel_engine' })
    event.remove({ id: 'ad_astra:steel_tank' })
    event.remove({ id: 'ad_astra:alloying/steel_ingot_from_alloying_iron_ingot_and_coals' })
    event.remove({ id: 'ad_astra:nasa_workbench/tier_2_rocket_from_nasa_workbench' })
    event.remove({ id: 'botania:petal_apothecary/entropinnyum' })
    event.remove({ id: 'computercraft:computer_command' })

    event.remove({ id: 'thermal:machines/press/press_enderium_ingot_to_coin' })
    event.remove({ id: 'thermal:machines/press/press_enderium_nugget_to_coin' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/enderium/coin_gold_cast' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/enderium/coin_sand_cast' })
    event.remove({ id: 'thermal:machines/press/press_signalum_ingot_to_coin' })
    event.remove({ id: 'thermal:machines/press/press_signalum_nugget_to_coin' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/signalum/coin_gold_cast' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/signalum/coin_sand_cast' })
    event.remove({ id: 'thermal:machines/press/press_lumium_ingot_to_coin' })
    event.remove({ id: 'thermal:machines/press/press_lumium_nugget_to_coin' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/lumium/coin_gold_cast' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/lumium/coin_sand_cast' })
    event.remove({ id: 'thermal:machines/press/press_netherite_ingot_to_coin' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/netherite/coin_gold_cast' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/netherite/coin_sand_cast' })

    event.remove({ id: 'botania:alfheim_portal' })
    event.remove({ id: 'create:crafting/materials/andesite_alloy' })
    event.remove({ id: 'create:crafting/materials/andesite_alloy_from_zinc' })
    event.remove({ id: 'create:mixing/andesite_alloy' })
    event.remove({ id: 'create:mixing/andesite_alloy_from_zinc' })
    event.remove({ id: 'tconstruct:compat/create/andesite_alloy_iron' })
    event.remove({ id: 'tconstruct:compat/create/andesite_alloy_zinc' })
    event.remove({ id: 'thermal:compat/create/smelter_create_alloy_andesite_alloy' })
    event.remove({ id: 'create:item_application/brass_casing_from_log' })
    event.remove({ id: 'create:item_application/brass_casing_from_wood' })
    event.remove({ id: 'create:item_application/brass_casing_from_log_using_deployer' })
    event.remove({ id: 'create:item_application/brass_casing_from_wood_using_deployer' })

    event.remove({ id: 'mekanism:bin/basic' })
    event.remove({ id: 'mekanism:bin/advanced' })
    event.remove({ id: 'mekanism:bin/elite' })
    event.remove({ id: 'mekanism:bin/ultimate' })
    event.remove({ id: 'mekanism_extras:bin/absolute' })
    event.remove({ id: 'mekanism_extras:bin/supreme' })
    event.remove({ id: 'mekanism_extras:bin/cosmic' })
    event.remove({ id: 'mekanism_extras:bin/infinite' })

    event.remove({ id: 'tfc_ie_addon:anvil/hammer_head' })
    event.remove({ id: 'tfc_ie_addon:anvil/wirecutter_head' })

    event.remove({ id: 'tconstruct:tables/crafting_station_from_logs' })
    event.remove({ id: 'tconstruct:tables/crafting_station' })
    event.remove({ id: 'tconstruct:tables/tinker_station' })
    event.remove({ id: 'tconstruct:tables/part_builder' })

    event.remove({ id: 'embers:mechanical_core' })
    event.remove({ id: 'embers:ember_activator' })
    event.remove({ id: 'embers:melter' })
    event.remove({ id: 'embers:stamper' })
    event.remove({ id: 'embers:alchemy_tablet' })

    event.remove({ id: 'integratedterminals:crafting/part_terminal_storage' })
    // event.remove({ id: 'rftoolsbuilder:builder' })

    event.remove({ id: 'compactmachines:wall' })
    event.remove({ id: 'oceanworld:sea_key' })

    event.remove({ id: 'botania:fertilizer_dye' })
    event.remove({ id: 'botania:apothecary_default' })
    event.remove({ id: 'botania:apothecary_forest' })
    event.remove({ id: 'botania:apothecary_plains' })
    event.remove({ id: 'botania:apothecary_mountain' })
    event.remove({ id: 'botania:apothecary_fungal' })
    event.remove({ id: 'botania:apothecary_swamp' })
    event.remove({ id: 'botania:apothecary_desert' })
    event.remove({ id: 'botania:apothecary_taiga' })
    event.remove({ id: 'botania:apothecary_mesa' })
    event.remove({ id: 'botania:apothecary_mossy' })
    event.remove({ id: 'botania:apothecary_livingrock' })
    event.remove({ id: 'botania:apothecary_deepslate' })

    event.remove({ id: 'botania:pure_daisy/livingrock' })
    event.remove({ id: 'botania:pure_daisy/livingwood' })
    event.remove({ id: 'botania:mana_pool' })

    event.remove({ id: 'ae2:network/blocks/inscribers' })
    event.remove({ id: 'jaopcaextras:inscriber.circuit.fluix' })
    event.remove({ id: 'jaopcaextras:inscriber.processor.fluix' })

    event.remove({ id: 'industrialforegoing:machine_frame_pity' })
    event.remove({ id: 'ad_astra:cryo_freezer' })
    event.remove({ id: 'jaopcaextras:inscriber.circuit.calorite' })

    event.remove({ id: 'cobblefordays:tier_1' })
    event.remove({ id: 'cobblefordays:tier_2' })
    event.remove({ id: 'cobblefordays:tier_3' })
    event.remove({ id: 'cobblefordays:tier_4' })
    event.remove({ id: 'cobblefordays:tier_5' })

    event.remove({ output: 'jaopca:gears.unknown' })
    event.remove({ output: 'jaopca:plates.unknown' })
    event.remove({ output: 'jaopca:circuits.unknown' })
    event.remove({ output: 'jaopca:processors.unknown' })
    event.remove({ output: 'jaopca:rods.unknown' })

    event.remove({ output: 'jaopca:circuits.iesnium' })
    event.remove({ output: 'jaopca:processors.iesnium' })

    event.remove({ output: 'nuclearcraft:plate_basic' })
    event.remove({ id: 'nuclearcraft:manufactory' })
    event.remove({ id: 'ars_nouveau:imbuement_chamber' })
    event.remove({ id: 'ars_nouveau:novice_spell_book' })
    event.remove({ id: 'ars_nouveau:apprentice_spell_book_upgrade' })
    event.remove({ id: 'ars_nouveau:ritual_brazier' })

    event.remove({ id: 'draconicevolution:components/draconium_core' })
    event.remove({ id: 'draconicevolution:components/wyvern_energy_core' })
    event.remove({ id: 'draconicevolution:compress/draconium_block' })
    event.remove({ id: 'botania:elven_trade/elementium' })
    event.remove({ id: 'industrialforegoing:mob_slaughter_factory' })
    event.remove({ id: 'industrialforegoing:fluid_laser_base' })
    event.remove({ id: 'industrialforegoing:dissolution_chamber/supreme_machine_frame' })
    event.remove({ id: 'occultism:crafting/chalk_red_impure' })
    event.remove({ id: 'ad_astra:nasa_workbench/tier_3_rocket_from_nasa_workbench' })

    event.remove({ id: 'thermal:machine_frame' })
    event.remove({ id: 'dimdungeons:recipe_block_gilded_portal' })
    event.remove({ id: 'modularrouters:modular_router' })
    event.remove({ id: 'sfm:cable' })
    event.remove({ id: 'sfm:manager' })
    event.remove({ id: 'fluxnetworks:fluxcore' })
    event.remove({ id: 'rftoolsbase:machine_frame' })

    event.remove({ id: 'malum:spirit_infusion/runic_workbench' })
    event.remove({ id: 'malum:spirit_infusion/void_tablet' })
    event.remove({ id: 'malum:spirit_altar' })

    event.remove({ id: 'forestry:sturdy_machine' })
    event.remove({ id: 'forestry:carpenter' })
    event.remove({ id: 'forestry:squeezer' })
    event.remove({ id: 'forestry:carpenter/hardened_casing' })
    event.remove({ id: 'forestry:fabricator/electron_tubes/flexible_casing' })
    event.remove({ id: 'jaopcaextras:inscriber.processor.calorite' })

    event.remove({ id: 'industrialforegoing:enchantment_factory' })
    event.remove({ id: 'industrialforegoing:enchantment_extractor' })
    event.remove({ id: 'industrialforegoing:enchantment_applicator' })
    event.remove({ id: 'industrialforegoing:ore_laser_base' })
    event.remove({ id: 'industrialforegoing:potion_brewer' })
    event.remove({ id: 'industrialforegoing:marine_fisher' })
    event.remove({ id: 'industrialforegoing:material_stonework_factory' })
    event.remove({ id: 'tiab:time_in_a_bottle' })

    event.remove({ id: 'integrateddynamics:crafting/logic_director' })
    event.remove({ id: 'rftoolsutility:flight_module' })
    event.remove({ id: 'botanicalmachinery:mana_emerald_block_decompress' })
    event.remove({ id: 'botanicalmachinery:mana_infusion/mana_emerald_block' })

    event.remove({ id: 'hostilenetworks:prediction_matrix' })

    event.remove({ id: 'deeperdarker:reinforced_echo_shard' })

    event.remove({ id: 'nuclearcraft:fusion_reactor_casing' })

    event.remove({ id: 'mythicbotany:rune_holder' })
    event.remove({ id: 'mythicbotany:central_rune_holder' })
    event.remove({ id: 'mythicbotany:kvasir_mead' })

    event.remove({ id: 'aetherworks:metal_former_block' })
    event.remove({ id: 'aetherworks:alchemy/aether_amalgam' })

    event.remove({ id: 'dustandash:crafting/ionizer' })
    event.remove({ id: 'nuclearcraft:rock_crusher/ancient_debris' })
    event.remove({ id: 'expatternprovider:water_cell' })
    event.remove({ id: 'expatternprovider:cobblestone_cell' })

    event.remove({ id: 'techreborn:crafting_table/parts/energy_flow_chip' })
    event.remove({ id: 'techreborn:crafting_table/parts/data_storage_chip' })
    event.remove({ id: 'techreborn:crafting_table/parts/data_storage_core' })
    
    event.remove({ id: 'mekanism:steel_casing' })
    event.remove({ id: 'mekanism:metallurgic_infusing/alloy/infused' })
    event.remove({ id: 'mekanism:control_circuit/basic' })
    event.remove({ id: 'draconicevolution:awakened_draconium_block' })
    event.remove({ id: 'mekanismgenerators:fission_reactor/casing' })
    event.remove({ id: 'mekanismgenerators:fission_reactor/fuel_assembly' })
    event.remove({ id: 'mekanism:isotopic_centrifuge' })
    event.remove({ id: 'mekanism:chemical_infuser' })
    event.remove({ id: 'mekanism:chemical_oxidizer' })
    event.remove({ id: 'mekanism:electrolytic_separator' })
    event.remove({ id: 'mekanism:configurator' })
    event.remove({ id: 'mekanism:transmitter/logistical_transporter/basic' })
    event.remove({ id: 'techreborn:crafting_table/machine_block/advanced_machine_casing_alt' })
    event.remove({ id: 'techreborn:crafting_table/machine_block/industrial_machine_casing_alt' })

    event.remove({ output: 'minecraft:furnace' })
    event.remove({ output: 'thermal:enderium_coin' })
    event.remove({ output: 'thermal:signalum_coin' })
    event.remove({ output: 'thermal:lumium_coin' })

    event.remove({ output: 'ars_nouveau:ritual_flight' })

    event.remove({ output: 'techreborn:advanced_alloy_ingot', not: { type: 'minecraft:crafting_shapeless' } })
    event.remove({ output: 'draconicevolution:awakened_draconium_ingot', not: { type: 'minecraft:crafting_shapeless' } })
    event.remove({ input: 'immersiveengineering:hammer', not: { id: 'immersiveengineering:crafting/survey_tools' } })

    event.remove({ output: '#cobblemon:poke_balls' })

    event.remove({ type: 'minecraft:crafting_shaped', output: '#forge:gears' })
    event.remove({ type: 'minecraft:crafting_shapeless', input: 'embers:tinker_hammer' })

})

MoreJSEvents.villagerTrades(event => {
    event.removeModdedTrades(["ars_nouveau:shady_wizard"], 3)
    event.removeModdedTrades(['techreborn:metallurgist'], 4)

})
