
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	enrichmentChamber = "2000000"
	#Base energy storage (Joules).
	osmiumCompressor = "8000000"
	#Base energy storage (Joules).
	combiner = "4000000"
	#Base energy storage (Joules).
	crusher = "2000000"
	#Base energy storage (Joules).
	metallurgicInfuser = "2000000"
	#Base energy storage (Joules).
	purificationChamber = "8000000"
	#Base energy storage (Joules).
	energizedSmelter = "2000000"
	#Base energy storage (Joules).
	digitalMiner = "5000000"
	#Base energy storage (Joules).
	electricPump = "4000000"
	#Base energy storage (Joules).
	chargePad = "204800000"
	#Base energy storage (Joules).
	rotaryCondensentrator = "2000000"
	#Base energy storage (Joules).
	oxidationChamber = "8000000"
	#Base energy storage (Joules).
	chemicalInfuser = "8000000"
	#Base energy storage (Joules).
	chemicalInjectionChamber = "16000000"
	#Base energy storage (Joules).
	electrolyticSeparator = "16000000"
	#Base energy storage (Joules).
	precisionSawmill = "2000000"
	#Base energy storage (Joules).
	chemicalDissolutionChamber = "16000000"
	#Base energy storage (Joules).
	chemicalWasher = "8000000"
	#Base energy storage (Joules).
	chemicalCrystallizer = "16000000"
	#Base energy storage (Joules).
	seismicVibrator = "2000000"
	#Base energy storage (Joules).
	pressurizedReactionBase = "200000"
	#Base energy storage (Joules).
	fluidicPlenisher = "4000000"
	#Base energy storage (Joules).
	laser = "200000000"
	#Base energy storage (Joules).
	laserAmplifier = "5000000000"
	#Base energy storage (Joules).
	laserTractorBeam = "5000000000"
	#Base energy storage (Joules).
	formulaicAssemblicator = "4000000"
	#Base energy storage (Joules).
	teleporter = "500000000"
	#Base energy storage (Joules).
	modificationStation = "4000000"
	#Base energy storage (Joules).
	isotopicCentrifuge = "8000000"
	#Base energy storage (Joules).
	nutritionalLiquifier = "4000000"
	#Base energy storage (Joules). Also defines max process rate.
	antiprotonicNucleosynthesizer = "100000000000"
	#Base energy storage (Joules).
	pigmentExtractor = "4000000"
	#Base energy storage (Joules).
	pigmentMixer = "8000000"
	#Base energy storage (Joules).
	paintingMachine = "4000000"
	#Base energy storage (Joules). Also defines max output rate.
	spsPort = "1000000000"
	#Base energy storage (Joules).
	dimensionalStabilizer = "4000000"

