#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon May 26 19:45:31 PDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=photon_v1.0a.zip
