#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jun 07 00:09:37 PDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=photon-main.zip
