#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 16 00:31:59 PDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound_r5.4_HTFC4_edition.zip
