const $Gson = Java.loadClass("com.google.gson.Gson")

const allBiomes = {
    "ad_astra:orbit": { mod: "ad_astra", temperature: -2.0 },
    "ad_astra:martian_wastelands": { mod: "ad_astra", temperature: -1.5 },
    "ad_astra:lunar_wastelands": { mod: "ad_astra", temperature: -2.0 },
    "ad_astra:martian_polar_caps": { mod: "ad_astra", temperature: -2.0 },
    "ad_astra:infernal_venus_barrens": { mod: "ad_astra", temperature: 10.0 },
    "ad_astra:glacio_snowy_barrens": { mod: "ad_astra", temperature: -1.5 },
    "ad_astra:mercury_deltas": { mod: "ad_astra", temperature: 10.0 },
    "ad_astra:glacio_ice_peaks": { mod: "ad_astra", temperature: -2.5 },
    "ad_astra:martian_canyon_creek": { mod: "ad_astra", temperature: -1.5 },
    "ad_astra:venus_wastelands": { mod: "ad_astra", temperature: 8.0 },
    "ae2:spatial_storage": { mod: "ae2", temperature: 0.2 },
    "ars_elemental:flashing_forest": { mod: "ars_elemental", temperature: 0.3 },
    "ars_elemental:blazing_forest": { mod: "ars_elemental", temperature: 0.4 },
    "ars_elemental:flourishing_forest": { mod: "ars_elemental", temperature: 0.4 },
    "ars_elemental:cascading_forest": { mod: "ars_elemental", temperature: 0.4 },
    "ars_nouveau:archwood_forest": { mod: "ars_nouveau", temperature: 0.3 },
    "biomesoplenty:auroral_garden": { mod: "biomesoplenty", temperature: -0.3 },
    "biomesoplenty:woodland": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:volcanic_plains": { mod: "biomesoplenty", temperature: 0.5 },
    "biomesoplenty:ominous_woods": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:grassland": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:fir_clearing": { mod: "biomesoplenty", temperature: 0.1 },
    "biomesoplenty:bog": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:crystalline_chasm": { mod: "biomesoplenty", temperature: 0.5 },
    "biomesoplenty:end_wilds": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:wetland": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:jacaranda_glade": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:rocky_shrubland": { mod: "biomesoplenty", temperature: 0.1 },
    "biomesoplenty:lavender_field": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:maple_woods": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:lush_savanna": { mod: "biomesoplenty", temperature: 0.6 },
    "biomesoplenty:dryland": { mod: "biomesoplenty", temperature: 0.5 },
    "biomesoplenty:glowing_grotto": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:gravel_beach": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:tundra": { mod: "biomesoplenty", temperature: -0.2 },
    "biomesoplenty:cold_desert": { mod: "biomesoplenty", temperature: -0.6 },
    "biomesoplenty:spider_nest": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:bayou": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:old_growth_dead_forest": { mod: "biomesoplenty", temperature: 1.8 },
    "biomesoplenty:end_corruption": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:wintry_origin_valley": { mod: "biomesoplenty", temperature: -0.3 },
    "biomesoplenty:visceral_heap": { mod: "biomesoplenty", temperature: 2.6 },
    "biomesoplenty:snowy_fir_clearing": { mod: "biomesoplenty", temperature: -0.3 },
    "biomesoplenty:origin_valley": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:crag": { mod: "biomesoplenty", temperature: 0.1 },
    "biomesoplenty:snowy_maple_woods": { mod: "biomesoplenty", temperature: -0.2 },
    "biomesoplenty:pasture": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:fungal_jungle": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:field": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:dune_beach": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:seasonal_forest": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:wasteland_steppe": { mod: "biomesoplenty", temperature: 0.1 },
    "biomesoplenty:redwood_forest": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:jade_cliffs": { mod: "biomesoplenty", temperature: 0.1 },
    "biomesoplenty:orchard": { mod: "biomesoplenty", temperature: 0.6 },
    "biomesoplenty:coniferous_forest": { mod: "biomesoplenty", temperature: 0.1 },
    "biomesoplenty:floodplain": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:highland": { mod: "biomesoplenty", temperature: -0.2 },
    "biomesoplenty:snowblossom_grove": { mod: "biomesoplenty", temperature: -0.4 },
    "biomesoplenty:mediterranean_forest": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:end_reef": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:undergrowth": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:rainforest": { mod: "biomesoplenty", temperature: 1 },
    "biomesoplenty:lush_desert": { mod: "biomesoplenty", temperature: 2.2 },
    "biomesoplenty:pumpkin_patch": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:dead_forest": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:prairie": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:snowy_coniferous_forest": { mod: "biomesoplenty", temperature: -0.4 },
    "biomesoplenty:rocky_rainforest": { mod: "biomesoplenty", temperature: 2.0 },
    "biomesoplenty:volcano": { mod: "biomesoplenty", temperature: 3.0 },
    "biomesoplenty:erupting_inferno": { mod: "biomesoplenty", temperature: 4.0 },
    "biomesoplenty:forested_field": { mod: "biomesoplenty", temperature: 0.3 },
    "biomesoplenty:withered_abyss": { mod: "biomesoplenty", temperature: 3.5 },
    "biomesoplenty:overgrown_greens": { mod: "biomesoplenty", temperature: 0.5 },
    "biomesoplenty:marsh": { mod: "biomesoplenty", temperature: 0.8 },
    "biomesoplenty:aspen_glade": { mod: "biomesoplenty", temperature: 0.4 },
    "biomesoplenty:mystic_grove": { mod: "biomesoplenty", temperature: 0.5 },
    "biomesoplenty:hot_springs": { mod: "biomesoplenty", temperature: 0.2 },
    "biomesoplenty:tropics": { mod: "biomesoplenty", temperature: 2.1 },
    "biomesoplenty:muskeg": { mod: "biomesoplenty", temperature: 0.8 },
    "biomesoplenty:old_growth_woodland": { mod: "biomesoplenty", temperature: 0.6 },
    "biomesoplenty:wasteland": { mod: "biomesoplenty", temperature: 2.7 },
    "biomesoplenty:scrubland": { mod: "biomesoplenty", temperature: 0.8 },
    "biomesoplenty:moor": { mod: "biomesoplenty", temperature: 0.8 },
    "biomesoplenty:shrubland": { mod: "biomesoplenty", temperature: 0.8 },
    "biomeswevegone:enchanted_tangle": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:frosted_taiga": { mod: "biomeswevegone", temperature: -0.5 },
    "biomeswevegone:forgotten_forest": { mod: "biomeswevegone", temperature: 0.4 },
    "biomeswevegone:dacite_ridges": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:frosted_coniferous_forest": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:dacite_shore": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:overgrowth_woodlands": { mod: "biomeswevegone", temperature: 0.7 },
    "biomeswevegone:firecracker_chaparral": { mod: "biomeswevegone", temperature: 0.8 },
    "biomeswevegone:sakura_grove": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:howling_peaks": { mod: "biomeswevegone", temperature: -0.2 },
    "biomeswevegone:bayou": { mod: "biomeswevegone", temperature: 0.7 },
    "biomeswevegone:mojave_desert": { mod: "biomeswevegone", temperature: 2.6 },
    "biomeswevegone:allium_shrubland": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:windswept_desert": { mod: "biomeswevegone", temperature: 2.0 },
    "biomeswevegone:sierra_badlands": { mod: "biomeswevegone", temperature: 1 },
    "biomeswevegone:rose_fields": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:cika_woods": { mod: "biomeswevegone", temperature: 0.4 },
    "biomeswevegone:amaranth_grassland": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:crimson_tundra": { mod: "biomeswevegone", temperature: -0.2 },
    "biomeswevegone:red_rock_peaks": { mod: "biomeswevegone", temperature: 0.4 },
    "biomeswevegone:black_forest": { mod: "biomeswevegone", temperature: 0.7 },
    "biomeswevegone:rugged_badlands": { mod: "biomeswevegone", temperature: 0.8 },
    "biomeswevegone:maple_taiga": { mod: "biomeswevegone", temperature: 0.4 },
    "biomeswevegone:ebony_woods": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:ironwood_gour": { mod: "biomeswevegone", temperature: 0.7 },
    "biomeswevegone:fragment_jungle": { mod: "biomeswevegone", temperature: 0.8 },
    "biomeswevegone:baobab_savanna": { mod: "biomeswevegone", temperature: 1.6 },
    "biomeswevegone:atacama_outback": { mod: "biomeswevegone", temperature: 1.4 },
    "biomeswevegone:orchard": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:eroded_borealis": { mod: "biomeswevegone", temperature: 0.3 },
    "biomeswevegone:coconino_meadow": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:jacaranda_jungle": { mod: "biomeswevegone", temperature: 0.8 },
    "biomeswevegone:shattered_glacier": { mod: "biomeswevegone", temperature: -0.5 },
    "biomeswevegone:tropical_rainforest": { mod: "biomeswevegone", temperature: 1.6 },
    "biomeswevegone:dead_sea": { mod: "biomeswevegone", temperature: 2.0 },
    "biomeswevegone:basalt_barrera": { mod: "biomeswevegone", temperature: 0.4 },
    "biomeswevegone:white_mangrove_marshes": { mod: "biomeswevegone", temperature: 0.8 },
    "biomeswevegone:rainbow_beach": { mod: "biomeswevegone", temperature: 0.7 },
    "biomeswevegone:lush_stacks": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:skyrise_vale": { mod: "biomeswevegone", temperature: 0.4 },
    "biomeswevegone:crag_gardens": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:redwood_thicket": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:zelkova_forest": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:weeping_witch_forest": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:temperate_grove": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:pumpkin_valley": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:red_rock_valley": { mod: "biomeswevegone", temperature: 0.6 },
    "biomeswevegone:coniferous_forest": { mod: "biomeswevegone", temperature: 0.2 },
    "biomeswevegone:canadian_shield": { mod: "biomeswevegone", temperature: -0.2 },
    "biomeswevegone:cypress_wetlands": { mod: "biomeswevegone", temperature: 0.8 },
    "biomeswevegone:prairie": { mod: "biomeswevegone", temperature: 0.5 },
    "biomeswevegone:aspen_boreal": { mod: "biomeswevegone", temperature: 0.3 },
    "biomeswevegone:araucaria_savanna": { mod: "biomeswevegone", temperature: 1 },
    "biomeswevegone:cypress_swamplands": { mod: "biomeswevegone", temperature: 0.7 },
    "cobgyms:cobgyms_biome": { mod: "cobgyms", temperature: 0.2 },
    "compactmachines:machine": { mod: "compactmachines", temperature: 0.2 },
    "deeperdarker:overcast_columns": { mod: "deeperdarker", temperature: 0.1 },
    "deeperdarker:blooming_caverns": { mod: "deeperdarker", temperature: 0.2 },
    "deeperdarker:echoing_forest": { mod: "deeperdarker", temperature: 0 },
    "deeperdarker:deeplands": { mod: "deeperdarker", temperature: -0.1 },
    "integrateddynamics:meneglin": { mod: "integrateddynamics", temperature: 0.2 },
    "mythicbotany:alfheim_lakes": { mod: "mythicbotany", temperature: 0.5 },
    "mythicbotany:golden_fields": { mod: "mythicbotany", temperature: 0.6 },
    "mythicbotany:alfheim_hills": { mod: "mythicbotany", temperature: 0.5 },
    "mythicbotany:dreamwood_forest": { mod: "mythicbotany", temperature: 0.4 },
    "mythicbotany:alfheim_plains": { mod: "mythicbotany", temperature: 0.5 },
    "nuclearcraft:wasteland": { mod: "nuclearcraft", temperature: 1 },
    "quark:glimmering_weald": { mod: "quark", temperature: 0.6 },
    "rats:ratlantis": { mod: "rats", temperature: 0.1 },
    "regions_unexplored:redstone_abyss": { mod: "regions_unexplored", temperature: 0.7 },
    "regions_unexplored:boreal_taiga": { mod: "regions_unexplored", temperature: -0.1 },
    "regions_unexplored:poppy_fields": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:deciduous_forest": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:old_growth_bayou": { mod: "regions_unexplored", temperature: 0.8 },
    "regions_unexplored:grassland": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:tropics": { mod: "regions_unexplored", temperature: 2.1 },
    "regions_unexplored:blackwood_taiga": { mod: "regions_unexplored", temperature: 0.1 },
    "regions_unexplored:ancient_delta": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:rocky_meadow": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:mauve_hills": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:clover_plains": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:spires": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:orchard": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:saguaro_desert": { mod: "regions_unexplored", temperature: 2.2 },
    "regions_unexplored:cold_boreal_taiga": { mod: "regions_unexplored", temperature: -0.2 },
    "regions_unexplored:silver_birch_forest": { mod: "regions_unexplored", temperature: 0.2 },
    "regions_unexplored:highland_fields": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:fen": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:frozen_tundra": { mod: "regions_unexplored", temperature: -0.3 },
    "regions_unexplored:bamboo_forest": { mod: "regions_unexplored", temperature: 0.7 },
    "regions_unexplored:sparse_redwoods": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:mycotoxic_undergrowth": { mod: "regions_unexplored", temperature: 0.2 },
    "regions_unexplored:maple_forest": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:joshua_desert": { mod: "regions_unexplored", temperature: 2.1 },
    "regions_unexplored:baobab_savanna": { mod: "regions_unexplored", temperature: 2.0 },
    "regions_unexplored:grassy_beach": { mod: "regions_unexplored", temperature: 0.7 },
    "regions_unexplored:dry_bushland": { mod: "regions_unexplored", temperature: 0.8 },
    "regions_unexplored:arid_mountains": { mod: "regions_unexplored", temperature: 0.9 },
    "regions_unexplored:mountains": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:alpha_grove": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:outback": { mod: "regions_unexplored", temperature: 0.8 },
    "regions_unexplored:scorching_caves": { mod: "regions_unexplored", temperature: 0.9 },
    "regions_unexplored:chalk_cliffs": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:cold_deciduous_forest": { mod: "regions_unexplored", temperature: 0.1 },
    "regions_unexplored:shrubland": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:pine_slopes": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:muddy_river": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:prismachasm": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:fungal_fen": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:tropical_river": { mod: "regions_unexplored", temperature: 2.1 },
    "regions_unexplored:ashen_woodland": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:autumnal_maple_forest": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:glistering_meadow": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:steppe": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:rocky_reef": { mod: "regions_unexplored", temperature: 0.7 },
    "regions_unexplored:redstone_caves": { mod: "regions_unexplored", temperature: 0.7 },
    "regions_unexplored:marsh": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:magnolia_woodland": { mod: "regions_unexplored", temperature: 0.7 },
    "regions_unexplored:flower_fields": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:eucalyptus_forest": { mod: "regions_unexplored", temperature: 0.8 },
    "regions_unexplored:pumpkin_fields": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:prairie": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:willow_forest": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:redwoods": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:rainforest": { mod: "regions_unexplored", temperature: 2.1 },
    "regions_unexplored:gravel_beach": { mod: "regions_unexplored", temperature: 0.7 },
    "regions_unexplored:towering_cliffs": { mod: "regions_unexplored", temperature: 0.3 },
    "regions_unexplored:pine_taiga": { mod: "regions_unexplored", temperature: -0.1 },
    "regions_unexplored:bioshroom_caves": { mod: "regions_unexplored", temperature: 0.3 },
    "regions_unexplored:cold_river": { mod: "regions_unexplored", temperature: -0.3 },
    "regions_unexplored:hyacinth_deeps": { mod: "regions_unexplored", temperature: 0.4 },
    "regions_unexplored:icy_heights": { mod: "regions_unexplored", temperature: -0.7 },
    "regions_unexplored:frozen_pine_taiga": { mod: "regions_unexplored", temperature: -0.4 },
    "regions_unexplored:sparse_rainforest": { mod: "regions_unexplored", temperature: 1.4 },
    "regions_unexplored:temperate_grove": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:blackstone_basin": { mod: "regions_unexplored", temperature: 0.6 },
    "regions_unexplored:barley_fields": { mod: "regions_unexplored", temperature: 0.5 },
    "regions_unexplored:bayou": { mod: "regions_unexplored", temperature: 0.7 },
    "regions_unexplored:golden_boreal_taiga": { mod: "regions_unexplored", temperature: -0.1 },
    "terralith:mountain_steppe": { mod: "terralith", temperature: 0.4 },
    "terralith:blooming_valley": { mod: "terralith", temperature: 0.5 },
    "terralith:frozen_cliffs": { mod: "terralith", temperature: -0.3 },
    "terralith:snowy_cherry_grove": { mod: "terralith", temperature: -0.1 },
    "terralith:valley_clearing": { mod: "terralith", temperature: 0.5 },
    "terralith:cave/desert_caves": { mod: "terralith", temperature: 0.9 },
    "terralith:cave/andesite_caves": { mod: "terralith", temperature: 0.4 },
    "terralith:cave/tuff_caves": { mod: "terralith", temperature: 0.4 },
    "terralith:hot_shrubland": { mod: "terralith", temperature: 1.6 },
    "terralith:alpine_highlands": { mod: "terralith", temperature: 0.2 },
    "terralith:alpha_islands_winter": { mod: "terralith", temperature: -0.2 },
    "terralith:moonlight_valley": { mod: "terralith", temperature: 0.5 },
    "terralith:fractured_savanna": { mod: "terralith", temperature: 1.4 },
    "terralith:warm_river": { mod: "terralith", temperature: 0.8 },
    "terralith:volcanic_crater": { mod: "terralith", temperature: 2.1 },
    "terralith:moonlight_grove": { mod: "terralith", temperature: 0.5 },
    "terralith:red_oasis": { mod: "terralith", temperature: 1 },
    "terralith:gravel_beach": { mod: "terralith", temperature: 0.6 },
    "terralith:skylands_summer": { mod: "terralith", temperature: 2.0 },
    "terralith:steppe": { mod: "terralith", temperature: 0.6 },
    "terralith:stony_spires": { mod: "terralith", temperature: 0.6 },
    "terralith:cave/mantle_caves": { mod: "terralith", temperature: 2.2 },
    "terralith:cave/thermal_caves": { mod: "terralith", temperature: 2.8 },
    "terralith:shrubland": { mod: "terralith", temperature: 0.5 },
    "terralith:highlands": { mod: "terralith", temperature: 0.4 },
    "terralith:alpha_islands": { mod: "terralith", temperature: 0.2 },
    "terralith:cloud_forest": { mod: "terralith", temperature: 0.7 },
    "terralith:windswept_spires": { mod: "terralith", temperature: 0.5 },
    "terralith:shield_clearing": { mod: "terralith", temperature: 0.5 },
    "terralith:brushland": { mod: "terralith", temperature: 0.7 },
    "terralith:cave/granite_caves": { mod: "terralith", temperature: 0.4 },
    "terralith:cave/fungal_caves": { mod: "terralith", temperature: 0.5 },
    "terralith:siberian_grove": { mod: "terralith", temperature: -0.2 },
    "terralith:scarlet_mountains": { mod: "terralith", temperature: 0.1 },
    "terralith:gravel_desert": { mod: "terralith", temperature: 0.6 },
    "terralith:cave/diorite_caves": { mod: "terralith", temperature: 0.4 },
    "terralith:rocky_shrubland": { mod: "terralith", temperature: 0.6 },
    "terralith:siberian_taiga": { mod: "terralith", temperature: -0.2 },
    "terralith:orchid_swamp": { mod: "terralith", temperature: 0.8 },
    "terralith:temperate_highlands": { mod: "terralith", temperature: 0.2 },
    "terralith:basalt_cliffs": { mod: "terralith", temperature: 0.4 },
    "terralith:glacial_chasm": { mod: "terralith", temperature: -0.3 },
    "terralith:desert_spires": { mod: "terralith", temperature: 2.0 },
    "terralith:skylands_winter": { mod: "terralith", temperature: -0.2 },
    "terralith:snowy_maple_forest": { mod: "terralith", temperature: -0.2 },
    "terralith:warped_mesa": { mod: "terralith", temperature: 0.8 },
    "terralith:wintry_forest": { mod: "terralith", temperature: -0.2 },
    "terralith:emerald_peaks": { mod: "terralith", temperature: 0.1 },
    "terralith:snowy_shield": { mod: "terralith", temperature: -0.2 },
    "terralith:sakura_grove": { mod: "terralith", temperature: 0.5 },
    "terralith:savanna_slopes": { mod: "terralith", temperature: 2.0 },
    "terralith:white_mesa": { mod: "terralith", temperature: 0.7 },
    "terralith:desert_oasis": { mod: "terralith", temperature: 1.6 },
    "terralith:cave/infested_caves": { mod: "terralith", temperature: 0.2 },
    "terralith:ashen_savanna": { mod: "terralith", temperature: 2.1 },
    "terralith:lush_desert": { mod: "terralith", temperature: 1.2 },
    "terralith:caldera": { mod: "terralith", temperature: 0.8 },
    "terralith:amethyst_rainforest": { mod: "terralith", temperature: 1 },
    "terralith:blooming_plateau": { mod: "terralith", temperature: 0.5 },
    "terralith:wintry_lowlands": { mod: "terralith", temperature: -0.2 },
    "terralith:shield": { mod: "terralith", temperature: 0.4 },
    "terralith:desert_canyon": { mod: "terralith", temperature: 2.2 },
    "terralith:rocky_mountains": { mod: "terralith", temperature: 0.6 },
    "terralith:lavender_valley": { mod: "terralith", temperature: 0.5 },
    "terralith:amethyst_canyon": { mod: "terralith", temperature: 0.4 },
    "terralith:cave/ice_caves": { mod: "terralith", temperature: -0.2 },
    "terralith:cave/frostfire_caves": { mod: "terralith", temperature: -0.3 },
    "terralith:white_cliffs": { mod: "terralith", temperature: 0.5 },
    "terralith:ancient_sands": { mod: "terralith", temperature: 2.1 },
    "terralith:arid_highlands": { mod: "terralith", temperature: 0.7 },
    "terralith:yellowstone": { mod: "terralith", temperature: 0.8 },
    "terralith:skylands_autumn": { mod: "terralith", temperature: 0.5 },
    "terralith:ice_marsh": { mod: "terralith", temperature: -0.2 },
    "terralith:granite_cliffs": { mod: "terralith", temperature: 0.4 },
    "terralith:yosemite_cliffs": { mod: "terralith", temperature: 0.4 },
    "terralith:tropical_jungle": { mod: "terralith", temperature: 2.1 },
    "terralith:lavender_forest": { mod: "terralith", temperature: 0.5 },
    "terralith:lush_valley": { mod: "terralith", temperature: 0.6 },
    "terralith:skylands_spring": { mod: "terralith", temperature: 0.4 },
    "terralith:painted_mountains": { mod: "terralith", temperature: 0.6 },
    "terralith:rocky_jungle": { mod: "terralith", temperature: 2.0 },
    "terralith:mirage_isles": { mod: "terralith", temperature: 0.5 },
    "terralith:cold_shrubland": { mod: "terralith", temperature: -0.2 },
    "terralith:savanna_badlands": { mod: "terralith", temperature: 1.6 },
    "terralith:snowy_badlands": { mod: "terralith", temperature: -0.3 },
    "terralith:yosemite_lowlands": { mod: "terralith", temperature: 0.4 },
    "terralith:skylands": { mod: "terralith", temperature: 0.4 },
    "terralith:alpine_grove": { mod: "terralith", temperature: 0.2 },
    "terralith:cave/deep_caves": { mod: "terralith", temperature: 0.2 },
    "terralith:cave/crystal_caves": { mod: "terralith", temperature: 0.2 },
    "terralith:bryce_canyon": { mod: "terralith", temperature: 0.4 },
    "terralith:haze_mountain": { mod: "terralith", temperature: 0.4 },
    "terralith:sakura_valley": { mod: "terralith", temperature: 0.5 },
    "terralith:birch_taiga": { mod: "terralith", temperature: 0.1 },
    "terralith:cave/underground_jungle": { mod: "terralith", temperature: 0.6 },
    "terralith:jungle_mountains": { mod: "terralith", temperature: 1 },
    "terralith:volcanic_peaks": { mod: "terralith", temperature: 2.0 },
    "terralith:sandstone_valley": { mod: "terralith", temperature: 0.5 },
    "terralith:forested_highlands": { mod: "terralith", temperature: 0.6 }
}


ItemEvents.rightClicked("minecraft:diamond", event => {
    const server = Utils.getServer()
    /**
     * @type {Internal.ResourceManager}
    */
    const manager = server.getResourceManager()
    const biomePath = "worldgen/biome/"

    for (const key in allBiomes) {
        let obj = allBiomes[key]
        let biomeMod = obj.mod
        let biomeName = key.split(':')[1]
        let rl = new ResourceLocation(biomeMod, biomePath + biomeName + ".json")
        let opt = manager.getResource(rl)
        if (opt.isPresent()) {
            let reader = opt.get().openAsReader()
            let gson = new $Gson()
            let jsonObj = gson["fromJson(java.io.Reader,java.lang.Class)"](reader, $JsonObject)

            jsonObj["addProperty(java.lang.String,java.lang.Number)"]("temperature", obj.temperature)

            console.log(`Biome: ${key}`)
            console.log(jsonObj)

            // let jsonOutput = JSON.stringify(jsonObj, null, 2)
            let outputPath = "biome_data/" + biomeMod + "/" + biomePath + biomeName + ".json"
            FilesJS.createDirectory("biome_data/" + biomeMod + "/" + biomePath)
            FilesJS.writeFile(outputPath, jsonObj.toString())
            // FilesJS.writeFile(outputPath, jsonOutput)
        } else {
            console.log(`Resource not found: ${rl}`)
        }
    }

})